image: ocaml/opam2:4.08

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
- opam switch
- opam depext conf-m4
- opam install -y -q . --deps-only

build:
  stage: build
  script:
  - dune build src/main.exe
  artifacts:
    paths:
    - _build

pages:
  stage: deploy
  script:
  - cd site
  - dune exec ../src/main.exe
  - mv public ../public
  artifacts:
    paths:
    - public
  only:
  - master
